//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 01:33:12 AM MSK 
//


package com.nyha.task2xml.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the papers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SciencePaper_QNAME = new QName("urn:papers", "science-paper");
    private final static QName _ArtPaper_QNAME = new QName("urn:papers", "art-paper");
    private final static QName _Paper_QNAME = new QName("urn:papers", "paper");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: papers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Paper }
     * 
     */
    public Paper createPaper() {
        return new Paper();
    }

    /**
     * Create an instance of {@link SciencePaper }
     * 
     */
    public SciencePaper createScience() {
        return new SciencePaper();
    }

    /**
     * Create an instance of {@link ArtPaper }
     * 
     */
    public ArtPaper createArt() {
        return new ArtPaper();
    }

    /**
     * Create an instance of {@link Papers }
     * 
     */
    public Papers createPapers() {
        return new Papers();
    }

    /**
     * Create an instance of {@link Chars }
     * 
     */
    public Chars createChars() {
        return new Chars();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SciencePaper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:papers", name = "science-paper", substitutionHeadNamespace = "urn:papers", substitutionHeadName = "paper")
    public JAXBElement<SciencePaper> createSciencePaper(SciencePaper value) {
        return new JAXBElement<SciencePaper>(_SciencePaper_QNAME, SciencePaper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArtPaper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:papers", name = "art-paper", substitutionHeadNamespace = "urn:papers", substitutionHeadName = "paper")
    public JAXBElement<ArtPaper> createArtPaper(ArtPaper value) {
        return new JAXBElement<ArtPaper>(_ArtPaper_QNAME, ArtPaper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Paper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:papers", name = "paper")
    public JAXBElement<Paper> createPaper(Paper value) {
        return new JAXBElement<Paper>(_Paper_QNAME, Paper.class, null, value);
    }

}
